# Generated by Django 6.0.1 on 2026-01-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_contributor',
            field=models.BooleanField(default=False, help_text='Designates whether this user can upload or submit content site-wide.'),
        ),
    ]
