# Generated by Django 6.0 on 2025-12-30 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLIPLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PLIPScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_classifier.pliplabel')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_classifier.plipsubmission')),
            ],
        ),
    ]
