# Generated by Django 6.0 on 2025-12-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0002_pliplabel_plipscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plipscore',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_scores', to='image_classifier.plipsubmission'),
        ),
    ]
