# Generated by Django 6.0 on 2025-12-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0003_alter_plipscore_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plipimage',
            name='md5',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pliplabel',
            name='label',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
