# Generated by Django 6.0 on 2026-01-02 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0004_alter_plipimage_md5_alter_pliplabel_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='plipimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='plipsubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
