# Generated by Django 6.0 on 2026-01-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0005_plipimage_created_at_plipsubmission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plipscore',
            name='score',
            field=models.FloatField(db_index=True),
        ),
    ]
