# Generated by Django 6.0 on 2026-01-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0006_alter_plipscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='plipsubmission',
            name='expected_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='image_classifier.pliplabel'),
        ),
        migrations.AlterField(
            model_name='plipscore',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='image_classifier.pliplabel'),
        ),
    ]
