# Generated by Django 6.0.1 on 2026-01-07 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0007_plipsubmission_expected_label_alter_plipscore_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plipsubmission',
            name='expected_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='image_classifier.pliplabel'),
        ),
    ]
